package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, 11 May, 2026 11:14:39 AM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String name);
} // interface ReverseOperations
